name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Publish articles on dev.to
        uses: "sinedied/publish-devto@30728bf"
        with:
          files: "_posts/2021-02-03-managing-css-in-angular-app-for-cross-browsers-and-os.md"
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}
          conventional_commits: true
