# name: Build every day
# on:
#   schedule:
#     - cron: "30 13 * * *" # 1:30 PM (UTC)/8:30 AM (EST)
#       #0 = Sunday, 1 = Monday, 2 = Tuesday, 3 = Wednesday, 4 = Thursday, 5 = Friday, 6 = Saturday
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: curl
#         uses: wei/curl@master
#         with:
#           args: "-X POST -H 'Authorization: token ${{ secrets.GH_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/rupeshtiwari/rupeshtiwari.github.io/pages/builds"
#           # args: "-X POST -H 'Authorization: token ${{ secrets.GH_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/YourUserName/YourRepository/pages/builds"
